### ISSUE TITLE
example "super-simple" errors at runtime on Windows

### ISSUE THREAD

**Issue by DoublePoly** [ggez/ggez#978]
I copied the "super-simple" example and I'm getting this error at runtime:
`Error: WindowCreationError(NotSupported("required extension \"WGL_ARB_create_context_profile\" not found"))`

here is my Cargo.toml:
```toml
[package]
name = "ggez_example"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6.0"
glam = { version = "0.17.3", features = [ "mint" ] }
```
